{% set name = "vispy" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eed8b44d6f5c87bd295b24aa9a2e0e4e6dc6a905ccee01b2d41c8fbf0a767b3d
  patches:
    - ctypes_fontconfig.diff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - numpy
    - fontconfig  # [unix]
    - cython
    - packaging
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - fontconfig  # [unix]
    - freetype-py
    - hsluv
    - kiwisolver
    - packaging

test:
  imports:
    - vispy
    # make sure that platform-specific dpi functions can be imported
    - vispy.util.dpi
    - vispy.util.fonts
  # TODO: check headless testing
  # requires:
  #  - pyqt >=5.0
  # commands:
  #  - python -c "import vispy; print(vispy.sys_info()); vispy.test()"

about:
  home: http://vispy.org/
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: VisPy is a high-performance interactive 2D/3D data visualization library.
  dev_url: https://github.com/vispy/vispy

extra:
  recipe-maintainers:
    - djhoese
    - kmuehlbauer
    - hmaarrfk
