{% set version = "0.6.0" %}

package:
  name: vispy
  version: {{ version }}

source:
  git_url: https://github.com/vispy/vispy
  # url: https://pypi.io/packages/source/v/vispy/vispy-{{ version }}.tar.gz
  # sha256: f6c36408df851b91322c928aadb2c8aaf3b31150e11f723784cc81b6280fdcc0


build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2-patch  # [win]
    - nodejs
  host:
    - python
    - pip
    - setuptools
    - fontconfig  # [unix]
    - numpy 1.11.3
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - fontconfig  # [unix]

test:
  imports:
    - vispy
  # todo: check headless testing
  #requires:
  #  - pyqt 5.*
  #commands:
  #  - python -c "import vispy; print(vispy.sys_info()); vispy.test()"

about:
  home: http://vispy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'VisPy is a high-performance interactive 2D/3D data visualization library.'

extra:
  recipe-maintainers:
    - kmuehlbauer
    - djhoese
