{% set version = "0.6.2" %}

package:
  name: vispy
  version: {{ version }}

source:
  fn: vispy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/v/vispy/vispy-{{ version }}.tar.gz
  sha256: c51a67fc1c9d31f2c4fea6338297b423659beedb51bc67b92d563ed8da0fe529
  patches:
    - ctypes_fontconfig.diff

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - numpy
    - fontconfig  # [unix]
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - fontconfig  # [unix]
    - freetype-py

test:
  imports:
    - vispy
  # todo: check headless testing
  #requires:
  #  - pyqt 5.*
  #commands:
  #  - python -c "import vispy; print(vispy.sys_info()); vispy.test()"

about:
  home: http://vispy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'VisPy is a high-performance interactive 2D/3D data visualization library.'

extra:
  recipe-maintainers:
    - djhoese
    - kmuehlbauer
