{% set name = "vispy" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 20c2b51c3fc6f2700a648ede8560376dabdc5d258184cef8f6a34b3b4c80e46f
  patches:
    - ctypes_fontconfig.diff

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - hatchling
    - hatch-vcs
    - hatch-cython
    # setuptools is needed by hatch-cython
    - setuptools
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - numpy
    - fontconfig  # [unix]
    - cython
    - packaging
  run:
    - python
    - fontconfig  # [unix]
    - freetype-py
    - hsluv
    - kiwisolver
    - packaging

test:
  imports:
    - vispy
    # make sure that platform-specific dpi functions can be imported
    - vispy.util.dpi
    - vispy.util.fonts
  # TODO: check headless testing
  # requires:
  #  - pyqt >=5.0
  # commands:
  #  - python -c "import vispy; print(vispy.sys_info()); vispy.test()"

about:
  home: http://vispy.org/
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: VisPy is a high-performance interactive 2D/3D data visualization library.
  dev_url: https://github.com/vispy/vispy

extra:
  recipe-maintainers:
    - brisvag
    - djhoese
    - kmuehlbauer
    - hmaarrfk
