{% set version = "0.5.3" %}

package:
  name: vispy
  version: {{ version }}

source:
  fn: vispy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/v/vispy/vispy-{{ version }}.tar.gz
  sha256: f6c36408df851b91322c928aadb2c8aaf3b31150e11f723784cc81b6280fdcc0
  patches:
    - ctypes_fontconfig.diff

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy
    - fontconfig  # [unix]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - fontconfig  # [unix]

test:
  imports:
    - vispy
  # todo: check headless testing
  #requires:
  #  - pyqt 4.*
  #commands:
  #  - python -c "import vispy; print(vispy.sys_info()); vispy.test()"

about:
  home: http://vispy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'VisPy is a high-performance interactive 2D/3D data visualization library.'

extra:
  recipe-maintainers:
    - djhoese
    - kmuehlbauer
