appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: y28ZF+s9JvFZhhpqgxVFEP7g80TNg7/E11TFjLS6ut9sIPiwyFu25YGCdfklBqK9DPsOrZgJhe8VYUgYtRfGCmR81xYH7IrHCZJHY5R2HaGijJ1Wk1WHbBKepKn46cGHmqOp7bW6mmpY/6qEkzXIuUXrsjBIy8NfmdjgsjIJhbzxXRCK6nnyec/x+CjZjtOhEcmD+beyTzXMKgTY16sAcWl4/EQn7bilc+pCjJj8DKmDnFFRv0ULMnU/PHc/GQ+d3XlcCMI62ZSKxgAw43uN0YzMKJ6IBJJW2mU5BfoxEN8Fm2aEJX/fb098BO+8ESTauc5qkrymdpEqoewi+RfYWoqxIUDY4eBOHhYCiPyq5eGYi98GWdGKg6lJ2W6Lo+F0rGGd65HtwEKQdwD4cYiOzrkpM9UBDuWJSFbmQgJwJGzPb5+qFIMDD6Qc3WFAMFJ2mdF7gW6Bwfv/1a3ZxFWq+s0Ekibzu/z431uUE2bSL+5qWpAP5As3wPD6UxrpQCY61H+nCgOEq48Dp7266W2d0Kqi5wbbqr4ZDCoNudka7VYqdPH5eTsv1+7nLJ98vWpD4hNV3etn0J1Akhp0wYZ9FjfqigJbCaXAlJKiwlttRA7A86XpCStCESyw0HC909qJsCbhSbEwznJc+1jutpgYhV4STjBi3yv+yvCYsKYZ8xY=}
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
  win: azure
conda_forge_output_validation: false
